Repository Woohahalife/KDT_BE7_Mini-Project, pull requests merged in 2024-04, with the labels that each got.

#83 JWT 예외처리를 위한 entrypoint 클래스 추가 및 보안 필터에 적용, refreshToken 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/common/config/RedisConfig.java
  src/main/java/com/core/miniproject/src/common/config/SecurityConfig.java
  src/main/java/com/core/miniproject/src/common/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtTokenGenerator.java
  src/main/java/com/core/miniproject/src/common/security/jwt/RefreshToken.java
  src/main/java/com/core/miniproject/src/common/security/jwt/RefreshTokenService.java
  src/main/java/com/core/miniproject/src/member/controller/MemberController.java
  src/main/java/com/core/miniproject/src/member/service/MemberService.java
  src/main/resources/application.yml
Labels: env, feat

#85 프론트엔드 요구사항 구현
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/core/miniproject/src/member/domain/entity/Member.java
  src/main/java/com/core/miniproject/src/member/service/MemberService.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationInsertResponse.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationListResponse.java
  src/main/resources/application.yml
Labels: feat, refactor

#86 feat: room update에 image 수정 추가
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/image/domain/entity/RoomImage.java
  src/main/java/com/core/miniproject/src/image/service/AccommodationImageService.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomRequest.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/repository/RoomRepository.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
Labels: feat

#87 fix: room update에 image 수정 기능
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
Labels: fix

#88 조회 메서드별 페이징 처리를 위한 Paging 추가, 쿼리문 개선
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/security/jwt/RedisRepository.java
  src/main/java/com/core/miniproject/src/image/domain/entity/RoomImage.java
  src/main/java/com/core/miniproject/src/image/service/AccommodationImageService.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/resources/application.yml
Labels: feat, refactor

#90 Feat#89
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/AccommodationType.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/image/domain/entity/AccommodationImage.java
  src/main/java/com/core/miniproject/src/image/repository/AccommodationImageRepository.java
  src/main/java/com/core/miniproject/src/location/domain/dto/LocationRequest.java
  src/main/java/com/core/miniproject/src/location/domain/dto/LocationResponse.java
  src/main/java/com/core/miniproject/src/location/domain/entity/LocationType.java
  src/main/java/com/core/miniproject/src/location/service/LocationService.java
Labels: fix

#94 fix: accommodation update 후 room 생성하고 accmmodation 조회 시 accommodation…
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
Labels: fix

#95 검색기능 고도화, 마이페이지 접속시 회원정보 조회 기능 구현
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/aspect/DateParamDefaultValueAspect.java
Labels: feat, refactor

#104 사용자 수정 기능 구현
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtTokenGenerator.java
  src/main/java/com/core/miniproject/src/member/controller/MemberController.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberUpdateRequest.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberUpdateResponse.java
  src/main/java/com/core/miniproject/src/member/domain/entity/Member.java
  src/main/java/com/core/miniproject/src/member/service/MemberService.java
Labels: feat

#106 숙소 조회 로직 개선 : 가격별 필터링 및 정렬 기능 추가
  scripts/deploy.sh
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/aspect/DateParamDefaultValueAspect.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomInsertRequest.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/main/resources/application.yml
Labels: env, feat

#108 숙소 검색시 가격조건 별 필터링 기능 롤백 맟 예약 쿼리 개선
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/aspect/DateParamDefaultValueAspect.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/reservation/repository/ReservationRepository.java
  src/main/java/com/core/miniproject/src/reservation/service/ReservationService.java
Labels: feat, refactor

#112 Feat#111
  README.md
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: fix

#115 멘토링 피드백 내용 반영 - 시큐리티 코드 개선
  src/main/java/com/core/miniproject/src/common/config/SecurityConfig.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtAuthenticationFilter.java
Labels: refactor

#117 Feat#116
  src/main/java/com/core/miniproject/src/board/controller/BoardController.java
  src/main/java/com/core/miniproject/src/board/controller/BoardPublicController.java
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardInsertRequest.java
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardInsertResponse.java
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardResponse.java
  src/main/java/com/core/miniproject/src/board/domain/entity/Board.java
  src/main/java/com/core/miniproject/src/board/repository/BoardRepository.java
  src/main/java/com/core/miniproject/src/board/service/BoardService.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/test/java/com/core/miniproject/src/board/repository/BoardRepositoryTest.java
Labels: feat

#120 fix: 공지사항 reponse 데이터 추가
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardInsertResponse.java
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardResponse.java
Labels: fix

#122 s3 이미지 업로드 기능 적용
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/ImageUrl.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/util/AccommodationUploader.java
  src/main/java/com/core/miniproject/src/common/util/RoomUploader.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomInsertRequest.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/room/RoomServiceTest.java
Labels: feat, refactor

#123 장바구니 등록 및 예약 기능 구현
  src/main/java/com/core/miniproject/src/accommodation/repository/SpringDataJpaAccommodationRepository.java
  src/main/java/com/core/miniproject/src/basket/controller/BasketController.java
  src/main/java/com/core/miniproject/src/basket/domain/dto/BasketCreateRequest.java
  src/main/java/com/core/miniproject/src/basket/domain/dto/BasketCreateResponse.java
  src/main/java/com/core/miniproject/src/basket/domain/dto/BasketDeleteRequest.java
  src/main/java/com/core/miniproject/src/basket/domain/dto/BasketReadResponse.java
  src/main/java/com/core/miniproject/src/basket/domain/entity/Basket.java
  src/main/java/com/core/miniproject/src/basket/repository/BasketRepository.java
  src/main/java/com/core/miniproject/src/basket/service/BasketService.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/reservation/controller/ReservationController.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationBasketRequest.java
  src/main/java/com/core/miniproject/src/reservation/repository/ReservationRepository.java
  src/main/java/com/core/miniproject/src/reservation/service/ReservationService.java
  src/main/java/com/core/miniproject/src/room/repository/RoomRepository.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: feat

#125 Feat#124
  src/main/java/com/core/miniproject/src/board/controller/BoardPublicController.java
  src/main/java/com/core/miniproject/src/board/repository/BoardRepository.java
  src/main/java/com/core/miniproject/src/board/service/BoardService.java
  src/test/java/com/core/miniproject/src/board/repository/BoardRepositoryTest.java
Labels: feat

#126 fix: Board 전체 개수 추가
  src/main/java/com/core/miniproject/src/board/controller/BoardPublicController.java
  src/main/java/com/core/miniproject/src/board/domain/dto/BoardAllResponse.java
  src/main/java/com/core/miniproject/src/board/repository/BoardRepository.java
  src/main/java/com/core/miniproject/src/board/service/BoardService.java
Labels: fix
