Repository Woohahalife/KDT_BE7_Mini-Project, pull requests merged in 2024-03, with the labels that each got.

#2 Feature/#1 Swagger API 적용 및 환경설정
  build.gradle
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: docs, env, feat

#4 h2 데이터베이스 설정
  src/main/resources/application.yml
  src/main/resources/templates/application-test.yml
  src/test/java/com/core/miniproject/MiniprojectApplicationTests.java
Labels: env

#7 공통 응답 모델 구현 & 전역 예외 처리 기능 구현 및 테스트
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/exception/BaseException.java
  src/main/java/com/core/miniproject/src/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponse.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/resources/application.yml
  src/test/java/com/core/miniproject/src/common/response/BaseResponseTest.java
Labels: feat

#10 회원 테이블 기반 회원가입 & 로그인 기능 구현
  build.gradle
  src/main/java/com/core/miniproject/src/common/config/JpaAuditingConfig.java
  src/main/java/com/core/miniproject/src/common/config/SecurityConfig.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/config/WebMvcConfig.java
  src/main/java/com/core/miniproject/src/common/constant/Role.java
  src/main/java/com/core/miniproject/src/common/entity/BaseEntity.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/common/security/AuthMemberResolver.java
  src/main/java/com/core/miniproject/src/common/security/JwtAuthentication.java
  src/main/java/com/core/miniproject/src/common/security/jwt/AccessToken.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtTokenGenerator.java
  src/main/java/com/core/miniproject/src/common/security/principal/MemberInfo.java
  src/main/java/com/core/miniproject/src/common/security/principal/MemberPrincipal.java
  src/main/java/com/core/miniproject/src/common/security/principal/MemberPrincipalService.java
  src/main/java/com/core/miniproject/src/member/controller/MemberController.java
  src/main/java/com/core/miniproject/src/member/controller/MemberPublicController.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberJoinRequest.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberJoinResponse.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberLoginRequest.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/core/miniproject/src/member/domain/dto/UserLoginResponse.java
  src/main/java/com/core/miniproject/src/member/domain/entity/Member.java
  src/main/java/com/core/miniproject/src/member/repository/MemberRepository.java
  src/main/java/com/core/miniproject/src/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/core/miniproject/src/common/response/BaseResponseTest.java
  src/test/java/com/core/miniproject/src/member/repository/MemberRepositoryTest.java
Labels: env, feat

#12 WebMvcConfig 수정, 기타 코드 style 수정
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/config/WebMvcConfig.java
  src/main/java/com/core/miniproject/src/member/service/MemberService.java
Labels: feat, refactor, style

#15 test : cicd 적용 테스트
  src/main/java/com/core/miniproject/src/member/controller/CICDTestController.java
Labels: test, feat

#16 Feat#8
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/AccommodationType.java
  src/main/java/com/core/miniproject/src/accommodation/repository/SpringDataJpaAccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/location/domain/dto/LocationRequest.java
  src/main/java/com/core/miniproject/src/location/domain/dto/LocationResponse.java
  src/main/java/com/core/miniproject/src/location/domain/entity/Location.java
  src/main/java/com/core/miniproject/src/location/domain/entity/LocationType.java
  src/main/java/com/core/miniproject/src/location/repository/SpringDataLocationRepository.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/rate/repository/SpringDataJpaRateRepository.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomRequest.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/repository/SpringDataJpaRoomRepository.java
  src/main/java/com/core/miniproject/src/roomprice/domain/RoomPrice.java
  src/main/java/com/core/miniproject/src/roomprice/repository/SpringDataJpaRoomPriceRepository.java
  src/test/java/com/core/miniproject/src/accommodation/repository/SpringDataJpaAccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/repository/SpringDataJpaRoomRepositoryTest.java
Labels: feat

#17 Feat#8
  src/test/java/com/core/miniproject/src/accommodation/repository/SpringDataJpaAccommodationRepositoryTest.java
Labels: refactor

#21 Feat#18
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/controller/RoomPublicController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomRequest.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/repository/SpringDataJpaRoomRepository.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/room/repository/SpringDataJpaRoomRepositoryTest.java
Labels: feat

#22 feat : reservation 엔티티 생성, reservation 레이어 별 클래스 생성(controller, serv…
  src/main/java/com/core/miniproject/src/common/constant/IsVisited.java
  src/main/java/com/core/miniproject/src/reservation/controller/ReservationController.java
  src/main/java/com/core/miniproject/src/reservation/model/entity/Reservation.java
  src/main/java/com/core/miniproject/src/reservation/repository/ReservationRepository.java
  src/main/java/com/core/miniproject/src/reservation/service/ReservationService.java
  src/test/java/com/core/miniproject/src/reservation/repository/ReservationRepositoryTest.java
Labels: feat

#25 reservation 등록(생성) 및 내역 조회 기능 구현
  src/main/java/com/core/miniproject/src/common/config/SecurityConfig.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/common/security/AuthMemberResolver.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/miniproject/src/member/controller/MemberPublicController.java
  src/main/java/com/core/miniproject/src/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/core/miniproject/src/member/domain/dto/UserLoginResponse.java
  src/main/java/com/core/miniproject/src/reservation/controller/ReservationController.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationInsertRequest.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationInsertResponse.java
  src/main/java/com/core/miniproject/src/reservation/model/dto/ReservationListResponse.java
  src/main/java/com/core/miniproject/src/reservation/model/entity/Reservation.java
  src/main/java/com/core/miniproject/src/reservation/repository/ReservationRepository.java
  src/main/java/com/core/miniproject/src/reservation/service/ReservationService.java
  src/test/java/com/core/miniproject/src/reservation/service/ReservationServiceTest.java
  src/test/java/com/core/miniproject/src/room/repository/SpringDataJpaRoomRepositoryTest.java
Labels: feat, style

#27 reservaion - member 간 외래키 제약조건 해제
  src/main/java/com/core/miniproject/src/reservation/model/entity/Reservation.java
  src/test/java/com/core/miniproject/src/reservation/repository/ReservationRepositoryTest.java
Labels: feat

#31 fix: 삭제로 인한 복구
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/location/repository/LocationRepository.java
  src/main/java/com/core/miniproject/src/rate/repository/RateRepository.java
  src/main/java/com/core/miniproject/src/room/repository/RoomRepository.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/main/java/com/core/miniproject/src/roomprice/repository/RoomPriceRepository.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: fix

#37 style : Location 생성 기능 구현 및 타입에 따른 Location 선택 조회 기능 repo 레이어 테스트 완료
  src/main/java/com/core/miniproject/src/location/controller/LocationController.java
  src/main/java/com/core/miniproject/src/location/domain/entity/Location.java
  src/main/java/com/core/miniproject/src/location/service/LocationService.java
  src/test/java/com/core/miniproject/src/location/repository/LocationRepositoryTest.java
Labels: feat, fix

#39 Feat#30 지역과 인원 수로 조회
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
Labels: feat

#40 테스트코드 일부 수정
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/location/domain/entity/Location.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/roomprice/domain/RoomPrice.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/reservation/service/ReservationServiceTest.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: refactor

#42 fix: RoomPrice Entity 관련 의존관계 제거-> Room Entity 의 column으로 변경
  src/main/java/com/core/miniproject/src/accommodation/repository/DiscountRepository.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/repository/RoomRepository.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: fix

#45 미사용 도메인 삭제(roomPrice), swagger ui 수정, build시 테스트 재실행
  .github/workflows/deploy.yml
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/miniproject/src/roomprice/domain/RoomPrice.java
  src/main/java/com/core/miniproject/src/roomprice/repository/RoomPriceRepository.java
Labels: refactor

#47 Feat#43
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/rate/domain/dto/RateInsertRequest.java
  src/main/java/com/core/miniproject/src/rate/domain/dto/RateInsertResponse.java
  src/main/java/com/core/miniproject/src/rate/domain/dto/RateRequest.java
  src/main/java/com/core/miniproject/src/rate/domain/dto/RateResponse.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/rate/repository/RateRepository.java
  src/main/java/com/core/miniproject/src/rate/service/RateService.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/rate/repository/RateRepositoryTest.java
Labels: feat, fix

#48 room 생성 기능 구현
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomInsertRequest.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomInsertResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/reservation/service/ReservationServiceTest.java
  src/test/java/com/core/miniproject/src/room/RoomServiceTest.java
Labels: feat

#50 Feat#43
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/rate/controller/RateController.java
  src/main/java/com/core/miniproject/src/rate/controller/RatePublicController.java
  src/main/java/com/core/miniproject/src/rate/repository/RateRepository.java
  src/main/java/com/core/miniproject/src/rate/service/RateService.java
Labels: feat

#55 rate - accommodation 연관관계 개선, 관련 쿼리 수정해 rate 평균값을 도메인 클래스에…
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomInsertResponse.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/RoomServiceTest.java
Labels: refactor

#53 Feat#43
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/room/controller/RoomPublicController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
Labels: fix

#57 swagger ui 가독성 수정, 그룹핑 해제
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationDiscountController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/main/java/com/core/miniproject/src/location/controller/LocationController.java
  src/main/java/com/core/miniproject/src/member/controller/MemberController.java
  src/main/java/com/core/miniproject/src/member/controller/MemberPublicController.java
  src/main/java/com/core/miniproject/src/rate/controller/RateController.java
  src/main/java/com/core/miniproject/src/rate/controller/RatePublicController.java
  src/main/java/com/core/miniproject/src/reservation/controller/ReservationController.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/controller/RoomPublicController.java
Labels: refactor

#58 room 배열로부터 최소 가격 산출 및 accommodaion 주입 로직 작성, 관련되는 레이어별 코드 수정 및 단위 테스트 검증
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationInsertResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/config/SwaggerConfig.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
Labels: feat, refactor, fix

#62 feat, refactor : 숙소 검색 기능 고도화 - 파라미터 default Value 설정
  src/main/java/com/core/miniproject/MiniprojectApplication.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/aspect/DateParamDefaultValueAspect.java
  src/main/java/com/core/miniproject/src/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/common/security/AuthMemberResolver.java
  src/main/java/com/core/miniproject/src/common/security/principal/MemberInfo.java
Labels: feat, refactor

#66 fix: 객실객체 배열 안에 room이 배열로 되도록 수정
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
Labels: fix

#68 숙소 단건 상세조회 기능 구현
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationPublicController.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
Labels: feat

#72 Accommodation - MultipleBagFetchException 해결
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
Labels: feat, refactor

#74 Feat#63
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Discount.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/java/com/core/miniproject/src/rate/domain/entity/Rate.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/repository/RoomRepository.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
  src/test/java/com/core/miniproject/src/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/core/miniproject/src/room/repository/RoomRepositoryTest.java
Labels: feat, fix

#76 JSON PARSE ERROR 전역 처리, 개발 서버 db mysql로 교체
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/core/miniproject/src/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/miniproject/src/common/response/BaseResponseStatus.java
  src/main/resources/application.yml
  src/main/resources/templates/application-test.yml
Labels: env, feat

#78 Feat#77
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationResponse.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomRequest.java
  src/main/java/com/core/miniproject/src/room/domain/dto/RoomResponse.java
  src/main/java/com/core/miniproject/src/room/domain/entity/Room.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
Labels: feat

#80 feat: Accommodation 기능 update 구현
  src/main/java/com/core/miniproject/src/accommodation/controller/AccommodationController.java
  src/main/java/com/core/miniproject/src/accommodation/domain/dto/AccommodationRequest.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Accommodation.java
  src/main/java/com/core/miniproject/src/accommodation/domain/entity/Discount.java
  src/main/java/com/core/miniproject/src/accommodation/repository/AccommodationRepository.java
  src/main/java/com/core/miniproject/src/accommodation/service/AccommodationService.java
  src/main/java/com/core/miniproject/src/location/domain/entity/Location.java
  src/main/java/com/core/miniproject/src/room/controller/RoomController.java
  src/main/java/com/core/miniproject/src/room/service/RoomService.java
Labels: feat
